server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: drive
          uri: http://localhost:8081
          predicates:
            - Path=/drives/**, 
        - id: Index
          uri: http://localhost:8082
          predicates:
            - Path=/indices/**, 
        - id: Notification
          uri: http://localhost:8083
          predicates:
            - Path=/notifications/**, 
        - id: Video Streaming
          uri: http://localhost:8084
          predicates:
            - Path=/videos/**, 
        - id: dashboard
          uri: http://localhost:8085
          predicates:
            - Path=, /dashBoardAttrs/**
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: drive
          uri: http://drive:8080
          predicates:
            - Path=/drives/**, 
        - id: Index
          uri: http://index:8080
          predicates:
            - Path=/indices/**, 
        - id: Notification
          uri: http://notification:8080
          predicates:
            - Path=/notifications/**, 
        - id: Video Streaming
          uri: http://videoStreaming:8080
          predicates:
            - Path=/videos/**, 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path=, /dashBoardAttrs/**
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
