apiVersion: apps/v1
kind: Deployment
metadata:
  name: Video Streaming
  labels:
    app: Video Streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Video Streaming
  template:
    metadata:
      labels:
        app: Video Streaming
    spec:
      containers:
        - name: Video Streaming
          image: username/Video Streaming:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
