apiVersion: apps/v1
kind: Deployment
metadata:
  name: Index
  labels:
    app: Index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Index
  template:
    metadata:
      labels:
        app: Index
    spec:
      containers:
        - name: Index
          image: username/Index:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
